apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert -c
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.network/comnet: "true"
    io.kompose.service: nginx
  name: nginx
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
      resources: {}
  restartPolicy: OnFailure
status: {}
